services:
  - type: web
    name: sqlemon
    env: python
    buildCommand: "pip install -r requirements.txt && python setup_db.py"
    startCommand: "gunicorn server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
